!$COLOR_BLUE = "#3063E9"
!$COLOR_BLACK = "#000000"
!$COLOR_PURPLE = "#CA58FF"
!$COLOR_ORANGE = "#ED7000"
!$COLOR_GREEN = "#138849"
!$COLOR_YELLOW = "#F5C625"
!$COLOR_RED = "#D23F47"
!$COLOR_WHITE = "#FFFFFF"
